### ISSUE TITLE
总要我写点什么

### ISSUE THREAD

**Issue by moiling** [simonla/ZhiHu#1]
总体感觉还是很棒的，很酷炫，用了很多design库的玩意
一些边距处理之类的还是很不错的
但还是有些地方让我不知所措
- 1.为毛要邮箱做用户名啊！别人都是好看的昵称，为毛我要是邮箱啊！
     我还以为用户名肯定登录不了了，谁知道我点个登录可以登进去啊！
- 2.不要乱弹Toast了，不过可能是我来的太早了，还是 开发版的缘故
- 3.头像上传再努把力吧！

很不错了已经！:smile:

**Comment by simonla** [comment]
谢谢学姐的鼓励，^ ^  
by the way，
1、重写了一个AutoCompleteTextView，感觉很炫酷
2、没错就是开发板。。。
3、已经在魅族mx5跑通了，兼容性问题太难搞了ORZ

**Comment by moiling** [comment]
:ok_hand:
